# Generated by ChatGPT on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="privacy_accepted",
            field=models.BooleanField(default=False, verbose_name="Согласие на ПДн"),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="privacy_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Согласие на ПДн (время)"),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="privacy_policy_version",
            field=models.CharField(blank=True, max_length=50, verbose_name="Версия политики ПДн"),
        ),
    ]

