# Generated by Django 5.1.15 on 2026-06-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='general', max_length=100, verbose_name='Категория')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, verbose_name='Анонс')),
                ('body', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(verbose_name='Содержимое (HTML)')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('h1', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='АО «Электроконтактор»', max_length=255, verbose_name='Название')),
                ('phone_main', models.CharField(default='(8672) 53-33-44', max_length=30, verbose_name='Телефон')),
                ('phone_sales', models.CharField(blank=True, max_length=30, verbose_name='Отдел сбыта')),
                ('email_main', models.EmailField(default='info@ekontaktor.ru', max_length=254, verbose_name='Email')),
                ('order_emails', models.TextField(default='info@ekontaktor.ru,elkonreal@yandex.ru', verbose_name='Email для заявок (через запятую)')),
                ('address', models.TextField(default='362003, г. Владикавказ, ул. Кабардинская, 8', verbose_name='Адрес')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквизиты')),
                ('webhook_url', models.URLField(blank=True, verbose_name='CRM Webhook URL')),
                ('yandex_metrika_id', models.CharField(blank=True, max_length=20, verbose_name='Яндекс.Метрика')),
                ('ga4_id', models.CharField(blank=True, max_length=30, verbose_name='GA4 ID')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
