# Generated by Django 5.1.15 on 2026-07-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sitesettings_phone_sales_length'),
        ('products', '0005_seo_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=120, verbose_name='Город')),
                ('region_name', models.CharField(blank=True, max_length=120, verbose_name='Регион')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, verbose_name='Приоритет')),
                ('is_indexable', models.BooleanField(default=False, help_text='True только при уникальном intro ≥ 400 символов', verbose_name='Индексировать')),
                ('intro_html', models.TextField(blank=True, verbose_name='Уникальный текст')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Город доставки',
                'verbose_name_plural': 'Города доставки',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_main',
            field=models.CharField(default='(8672) 54-01-03', max_length=30, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, verbose_name='Анонс')),
                ('body', models.TextField(verbose_name='Текст (HTML)')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='Отрасль')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='case_studies', to='products.productgroup', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Кейс / объект',
                'verbose_name_plural': 'Кейсы и объекты',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CityCategoryLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_html', models.TextField(blank=True, verbose_name='Уникальный текст')),
                ('is_indexable', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_landings', to='products.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_landings', to='content.deliverycity')),
            ],
            options={
                'verbose_name': 'Регион × категория',
                'verbose_name_plural': 'Региональные посадочные',
                'constraints': [models.UniqueConstraint(fields=('city', 'category'), name='uniq_city_category_landing')],
            },
        ),
    ]
