# Generated by Django 5.1.15 on 2026-06-30 10:53

import apps.docs.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to=apps.docs.models.document_upload_path, verbose_name='Файл')),
                ('uuid_filename', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('doc_type', models.CharField(choices=[('passport', 'Паспорт'), ('certificate', 'Сертификат'), ('drawing_dwg', 'Чертёж DWG'), ('drawing_pdf', 'Чертёж PDF'), ('catalog', 'Каталог'), ('tu', 'ТУ')], default='passport', max_length=20, verbose_name='Тип')),
                ('language', models.CharField(default='ru', max_length=5, verbose_name='Язык')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='docs.document')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.productgroup')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Документ товара',
                'verbose_name_plural': 'Документы товаров',
                'ordering': ['sort_order'],
            },
        ),
    ]
