# Generated by ChatGPT on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="marketing_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="marketing_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="privacy_policy_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
    ]

