# Generated by Django 5.1.15 on 2026-06-30 10:53

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('h1', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('noindex', models.BooleanField(default=False, verbose_name='Noindex')),
                ('canonical_override', models.CharField(blank=True, max_length=500, verbose_name='Canonical URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание (HTML)')),
                ('series_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Код серии')),
                ('product_type', models.CharField(choices=[('KT', 'КТ (переменный ток)'), ('KTP', 'КТП (постоянный ток)'), ('KTE', 'КТЭ (электротранспорт)'), ('ACCESSORY', 'Аксессуар'), ('SWITCH', 'Выключатель'), ('CAM', 'Кулачковый элемент'), ('OTHER', 'Прочее')], db_index=True, default='KT', max_length=20, verbose_name='Тип')),
                ('nominal_current_a', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Ном. ток, А')),
                ('nominal_voltage_v', models.PositiveIntegerField(default=380, verbose_name='Ном. напряжение, В')),
                ('poles', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Полюса')),
                ('application_category', models.CharField(blank=True, max_length=50, verbose_name='Категория применения')),
                ('designation_structure', models.TextField(blank=True, verbose_name='Структура обозначения (HTML)')),
                ('honest_sign', models.BooleanField(default=False, verbose_name='Честный знак')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('h1', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_groups', to='products.category', verbose_name='Категория')),
                ('related_groups', models.ManyToManyField(blank=True, related_name='related_to', to='products.productgroup', verbose_name='Связанные товары')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_key', models.SlugField(max_length=100, verbose_name='Ключ')),
                ('spec_value', models.CharField(max_length=255, verbose_name='Значение')),
                ('spec_unit', models.CharField(blank=True, max_length=20, verbose_name='Единица')),
                ('filterable', models.BooleanField(default=False, verbose_name='В фильтре')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.productgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['sort_order', 'spec_key'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Артикул')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('execution', models.CharField(choices=[('B', 'Б'), ('BS', 'БС'), ('S', 'С'), ('NONE', '—')], db_index=True, default='NONE', max_length=10, verbose_name='Исполнение')),
                ('coil_type', models.CharField(choices=[('AC', 'Переменный'), ('DC', 'Постоянный'), ('NONE', '—')], default='NONE', max_length=10, verbose_name='Тип катушки')),
                ('coil_voltage_v', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Напряжение катушки, В')),
                ('aux_contacts', models.CharField(blank=True, max_length=50, verbose_name='Всп. контакты')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена, ₽')),
                ('price_valid_from', models.DateField(blank=True, null=True, verbose_name='Цена действует с')),
                ('weight_net_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес нетто, кг')),
                ('weight_gross_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес брутто, кг')),
                ('dimensions', models.JSONField(blank=True, default=dict, verbose_name='Габариты')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ'), ('discontinued', 'Снят с производства')], default='in_stock', max_length=20, verbose_name='Наличие')),
                ('is_default', models.BooleanField(default=False, verbose_name='Вариант по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('search_vector', models.TextField(blank=True, editable=False, verbose_name='Search index')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Вариант (SKU)',
                'verbose_name_plural': 'Варианты (SKU)',
                'ordering': ['group', 'sku_code'],
            },
        ),
        migrations.AddIndex(
            model_name='productgroup',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_b07a68_idx'),
        ),
        migrations.AddIndex(
            model_name='productgroup',
            index=models.Index(fields=['nominal_current_a', 'is_active'], name='products_pr_nominal_d7d967_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productspec',
            unique_together={('group', 'spec_key')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['execution', 'coil_voltage_v'], name='products_pr_executi_35d26e_idx'),
        ),
    ]
