# Generated by Django 5.1.15 on 2026-07-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productgroup_image_rotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Карточка товара', 'verbose_name_plural': 'Карточки товаров'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['group', 'sku_code'], 'verbose_name': 'Вариант (цена и исполнение)', 'verbose_name_plural': 'Варианты и цены'},
        ),
        migrations.AlterField(
            model_name='category',
            name='h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок на странице'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Описание для поисковиков'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок для поисковиков'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок на странице'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='image_rotation',
            field=models.PositiveSmallIntegerField(default=0, help_text='Отображение на сайте: 0, 90, 180 или 270. Настраивается кнопками в админке.', verbose_name='Поворот фото (градусы)'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Описание для поисковиков'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок для поисковиков'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productgroup', verbose_name='Карточка товара'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.productgroup', verbose_name='Карточка товара'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='spec_key',
            field=models.SlugField(max_length=100, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productgroup', verbose_name='Карточка товара'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Адрес варианта'),
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.productgroup', verbose_name='Карточка товара')),
            ],
            options={
                'verbose_name': 'FAQ товара',
                'verbose_name_plural': 'FAQ товаров',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
